<a href="https://colab.research.google.com/github/ttussing/US-Gun-Exploration-Visualization/blob/master/Gun_Laws_and_Deaths_in_the_US.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Legal Gun Owners Still Kill People

An exploratory analysis of the effect of gun laws in the United States indicates that differences in the number of gun laws does indeed correspond to differences in gun related deaths.  These visualizations are produced to inform legislaters and voters about the relationship between gun legislation and gun related deaths. 



---


Contributors: Kevin Chang, May Jai, Laura Klipp, Bryan Tamsir, Hale Tussing

## Introduction

We wanted to look at the relationship between legal gun ownership and deaths by firearms.  When there is gun violence in the US, legal gun ownership is consistently written off as not the issue.  Instead, illegal gun ownership is blamed as the source of deaths by guns in the US.  This series of visualizations hopes to examine this assumption.

## The United States is the world leader in gun deaths by legally owned guns

The United States is the clear leader in homicides by personally owned guns and is well above average for the 185 countries in the world dataset. The *Homicides by Firearms* variable is calculated as the percentage of homicides by committed by firearms multiplied by the average number of firearms (per 100 people) in each country.  This serves as a proxy for the number of homicides by legally obtained guns. 



![World Gun Homicides](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/Homicides%20by%20Personally%20Owned%20Guns.png)

## Each State has Unique Levels of Gun Ownership, Gun Laws and Therefore Differences in Gun-Related Deaths

The data set depicts the number of gun-related deaths per state,  per year from 1991 thru 2018. We walk through different features of this dataset to show how state-level gun laws affect deaths per capita. 

---

```


```

**While we see that the United States has a problem with the number of deaths by legally owned guns, the United States is a diverse country with a wide range of deaths per capita.** 

![Mapping DPC](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/Deaths_by_state.png)

```


```
**Individual state's average deaths per capita have varying numbers of gun laws in effect. The states with more deaths per capita have far fewer gun laws.**

If we assume that states with more relaxed gun laws have higher levels of gun ownership, we see a similarity between the state gun deaths and the previous world dataset -- when gun laws are lax or there are more gun owners, there are more deaths per capita.   

![Mirror Chart of Gun Laws/DPC](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/KC_States_fewer.png)

```


```

**There is a drastic difference in the number of deaths per capita between states with relaxed gun laws and states with strict gun laws, and it's only getting more severe.**

The previous visualization shows that there are differences in the gun laws and the deaths per capita, so we grouped the states into either having less gun regulation (2-49 laws) or states with greater gun regulation (50-106 laws).  We see stark differences in the deaths per capita over time when looking at these two groupings of states. We also see a recent increasing trend in deaths per capita with states that have fewer gun laws.  
![Deaths per Capita Over Time](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/DPC%20over%20time.png)

```


```

**Gun related deaths in the US are mostly represented by homicides and suicides, and both categories have far more deaths in states with less gun regulation.**

The relationship between gun laws and deaths per capita persists when the cause of death is divided between homicides and suicides. While we can't further analyze the suicide rates, we can take a deeper look into homicides by looking at mass shootings. 


![Homicides and Suicides](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/Homicides%20and%20Suicides.png)

## A Look Into Mass Shootings: Gun Laws Still Matter

The data set depicts information on mass shootings carried out between 2013 and 2017.  Mass shootings are the most convtroversial, most discussed part of gun violence in the US.  We wanted to see if gun laws would still make a difference for this hot button topic.

---

**Gun laws affect not just gun ownership, but the number of mass shootings**

We grouped sates into two categories: those with <50 gun laws, and those with >50 gun laws.  Unsurprisingly, we found that states with less gun laws have higher gun ownership.  However, we also found that in states with less gun laws, there is a noticeably higher number of mass shootings.  When placed side by side, the relationships in these graphs looks strikingly similar.  

![gun_law_shootings](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_numLaw_Revised.png)

**Mass shootings are more lethal in states that lax their gun laws**

Is there a solution in sight?  We know that a state's gun laws can be changed, and so we looked at three groups of states: those whose gun laws increased, decreased, or stayed the same.  Where gun control was relaxed, more people died by guns per capita, and the average mas shooting was more dangerous.  The message is simple: legal gun ownership is still dangerous.

![gun_law_change_shootings](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_changeLaw_revised.png)

**States where gun control is significantly relaxed become more dangerous**

Over the course of 5 years, a few states have moved to decrease gun laws, so 
 we wanted to see what happened when a state made significant (>1) decrease. When guns become easier to purchase, more people are killed by firearms.

![decreas_law](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_lawDe_revised.png)

**When gun laws are repealed, more people die from guns**

Knowing our audience, we wanted to drive the point home by giving specific case studies where making a change had an effect. Missouri and Idaho are two states showing the repercussions of decreasing gun laws.

![case_study_decrease](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_CaseStudy_decrease_revised.png)

**When states add more gun laws, fewer people are killed by guns**

Making the point even clearer, we wanted to showcase states that showed a positive return on action. In both Delaware and Oregon, as the number of gun laws increased, the fewer deaths existed.

![case_study_increase](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_CaseStudy_increase_revised.png)


---

## Outro 

Gun violence is a controversial topic in the US, but legal gun ownership has been kept safe from scrutiny.  

While we were not able to prove that more gun laws cause more or less gun deaths, we showed that the two variables tend to move in opposite directions.  This was true when looking at statewide data, as well as when looking at mass shooting specifically.  To really understand how laws affect gun violence, we would delve deeper to test the causal nature of laws and gun deaths.  

We hope that this project serves to examine the popular talking points about legal gun ownership, and its role in a safer America.

## Making-of Documentation

The U.S. gun laws analysis went through multiple steps to arrive at the final output. See comparisons of versions below for each of the visualizations. 


```
   
```

Overall, the asthetic choices we made in our final versions to tie together the theme and maintain consistency throughout the visualizations were:

1. All colors throughout each of the charts are in the theme of a dark crimson red to represent any variable related to a greater number of deaths. The dark yellow was chosen as the other color because it is still on the same side of the color spectrum as red, so it does not represent an opposite of red, but rather a less extreme variable. While not all of these variables are exactly the same throughout each of the visualizations, we still wanted to maintain the same color scheme throughout, and using red to draw the readers attention to our main points. 
2. The final versions of the charts have horizontal legends directly below the x-axis in order to not distract from the main part of the visualization or titles. We believe that the first impression the reader should have is of the overall visualization and title. Then as the reader is looking for more detailed information when reading the axis labels and numerical values, they can also see what each of the colors represents in that chart. 
3. The legend title was taken out of the visualizations because the meaning of the legends is clear without showing the title.
4. Charts that have any explanations necessary are now included in a caption at the bottom of the graph to ensure that all necessary information is at the readers disposal while looking at the visualization.

### For the chart that explores the amount of gun related deaths over time in states with < 50 gun laws and states with ≥ 50 gun laws:


---


```


```

![World Firearms First Version](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/old_images/world_firearm1st.png)

**Changes Made:**
* The final vizualization standardized the color scheme to just dark crimson and orange to establish the color scheme that will be used throughout the project. 
* Instead of a color gradient for Hom Firearms, only the two colors were used to simply highlight the United States as having the highest homicides by firearms. 
* An average line with 95% confidence interval was added simply to establish a baseline reference point with respect to other countries and really show just how much of an outlier the United States is. 
* A descriptive caption was added that details an overall description chart attributes.  

![World Firearms Final Version](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/Homicides%20by%20Personally%20Owned%20Guns%20Final.png)

### For the chart that explores the amount of gun related deaths over time in states with < 50 gun laws and states with ≥ 50 gun laws:


---


```


```



![Gun Deaths over Time First Version](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/old_images/state_gun_law_deaths.png)

**Changes Made:**
* The y-axis data was changed from number of deaths to deaths per capita to ensure consistency with our other graphs. While both show essentially the same shape over time, ....
* The categories for each of the colors was changed to be ≥ 50 Gun Laws and <50 Gun Laws so that the reader has a better understanding of what the variable means instead of the arbitrary categories of High and Low gun laws. Even though the grouped variables didn't change, this adds clarity to the graph.

![Deaths per Capita over Time First Version](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/DPC%20over%20time.png)

### For the chart that explores the gun related causes of deaths in states with < 50 gun laws and states with ≥ 50 gun laws:


---


```


```



![Homicides and Suicides First Version](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/old_images/fewer_gun_laws_more_deaths.png)

**Changes Made:**
* Since the point of this visualization was to see the main categories of gun related deaths and to reiterate that states with fewer gun laws cause the majority of gun related deaths, we decided that the unintentional category was unneccesary in making this point, and therefore was ommitted from the chart. 
* The data on the x-axis is now deaths per capita instead of the interaction of deaths per capita and gun ownership. This is consistent with many of our other graphs and the interaction term doesn't add any value in making our point in this graph. 
* The smaller amount of deaths in states with greater than 50 gun laws was moved to the left side of the graph, making it easier to see the deaths per captia in each of the categories in the stacked bar chart. 
* The categories for each of the colors was changed to be **≥ 50 Gun Laws** and  **<50 Gun Laws** so that the reader has a better understanding of what the variable means instead of the arbitrary categories of High and Low gun laws. Even though the grouped variables didn't change, this adds clarity to the graph. 

![Homicides and Suicides Final Version](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/Homicides%20and%20Suicides.png)

### For charts that compare average gun ownership and number of mass shootings for states with <50 gun laws to states with ≥50 gun laws:



---



```


```



<img src="https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/old_images/ms_lawgroups.png" width="600" height="600">

**Changes Made:**
*   The chart was rotated from horizontal to vertical, making it consistent with the previous charts. We can still compare each bar easily, but the bars are thinner and take up less space. It now fits clearly on the screen while scrolling. 
*   The two previous titles were combined since the two bar charts are proving the same argument. 
*   Grid lines were removed because they are unneccessary to understand the chart and the background is less busy without them.
*   Field labels were hidden for the rows to avoid redundancy, since the meaning of the rows is already explained in the legend and the caption. 
* The categories for each of the colors was changed to be **≥ 50 Gun Laws** and  **<50 Gun Laws** so that the reader has a better understanding of what the variable means instead of the arbitrary categories of High and Low gun laws. Even though the grouped variables didn't change, this adds clarity to the graph. 


```

```

![gun_law_shootings](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_numLaw_Revised.png)

### For charts that compare average killed in mass shootings by gun owner and average deaths per capita for states that increased gun laws to states that decreased gun laws:


---


```


```



<img src="https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/old_images/ms_lawdiff.png" width="600" height="600">

**Changes Made:**
* The chart was rotated from horizontal to vertical: to make it consistent with the previous charts. It is still compare each group easily, but the bars are thinner and chart took less space so everything is clear without the need of scrolling up and down after the revision.
* The title of the two bar charts was combined to make the chart look cleaner, since both bar charts are there to prove the same argument. The title was changed to focus on the states that decreased gun laws instead of those increased to make the argument in the same direction as our other arguments.
* Grid lines were removed because they are unneccessary to understand the chart and the background is less busy without them.
* Field labels were hidden for rows to avoid redundancy, since the meaning of the rows is already explained in the legend and the caption making the chart look cleaner. 
* The y-axis label of the old left chart was changed to specify that these were from mass shootings.

```


```
![gun_law_change_shootings](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_changeLaw_revised.png)

### For the case study charts that explore states who changed their gun laws:


---


```


```

![Case Study 1](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/old_images/states_examples.png)


**Changes Made:**
* A chart was added to show the aggregate change of deaths per capita of all the states that decreased laws between 2013 and 2017. 
* The original two state charts depicting the effect of either increasing or deacreasing the number of gun laws, was changed to show 2 examples of each side of the argument. 
* The line colors were changed to the red and gold color scheme for consistency.
* The titles were impoved by making them more declarative and impactful. 
* The right y-axis was changed to deaths per capita instead of shot x gun owner to focus on the change of deaths per capita as we did in other charts. 
* The left y-axis title was changed to make the naming consistent with other charts.
* Grid lines were removed because they are unneccessary to understand the chart and the background is less busy without them.

![decreas_law](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_lawDe_revised.png)

---

![case_study_decrease](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_CaseStudy_decrease_revised.png)

---

![case_study_increase](https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/images/MS_CaseStudy_increase_revised.png)

# Data Sources and Data Cleaning

We have three main data sets:
1. **World firearms data** containing information about 185 countries' homicides and gunownership
2. **United States firearms data** containing information about the number of gun related deaths per state per year from 1999 to 2017
3. **United States Mass Shootings data** containing every mass shooting in the United State from 2013 to 2019

We used accessory data sets to join with some of these data sets in order to provide a richer depth of analysis. 

Additional data sets:
1. **Gun ownership per state**
2. **Firearm laws per state**

In [0]:
import pandas as pd
import numpy as np
from datetime import datetime
from IPython.display import Image

In [0]:
world_url = 'https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/data/World_firearms.csv'
state_url = 'https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/data/All_Firearm_Deaths_State_Year.csv'
state_owner_url = 'https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/data/Gun_Owner_Statistics_Per_State.csv'
state_laws_url = 'https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/data/gun_laws_data.csv'
state_code_url = 'https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/data/states.csv'
ms_url = 'https://raw.githubusercontent.com/ttussing/US-Gun-Exploration-Visualization/master/data/Mass_Shooting_Data_2013-2019.csv'
df_world = pd.read_csv(world_url)
df_state = pd.read_csv(state_url)
df_st_owner = pd.read_csv(state_owner_url)
df_state_laws = pd.read_csv(state_laws_url)
df_state_code = pd.read_csv(state_code_url)
df_ms = pd.read_csv(ms_url)

## World Firearms Data
Allows us to see which countries have the highest firearm ownership rates and which have the highest murder rates.

[Article Describing the Data Set](https://www.theguardian.com/news/datablog/2012/jul/22/gun-homicides-ownership-world-list#data)


---



**Description of the Dataset:**

- A collection of data about the world's firearms murders and gun ownership statistics were compiled in a [Google Sheet](https://docs.google.com/spreadsheets/d/1chqUZHuY6cXYrRYkuE0uwXisGaYvr7durZHJhpLGycs/edit#gid=0). 
- The data is compiled from 2 data sources:

  - The data on firearm homicides was collected by the UNODC through its annual crime survey. This includes the percent of homicides from using a firearm, the number of homicides from using a firearm, and the rate of homicide rate per 100,000 in the population. 
   
  - The data on gun ownership was collected by the small arms survey. This includes the average firearms per 100 people, the average number of civilian firearms, and rank by the rate of gun ownership. The data has been normalized for a rate per 100,000 population. 

- Limitations:
  - Data is missing for Russia, China, and Afghanistan
  - While the Google Spreadsheet says that it is being automatically updated every 5 minutes, the columns for homicide per country that was collected from the UNODC doesn't have information about what year it is for.
   - The data is from an annual crime survey, and it doesn't say if the numbers are being averaged across all years, or if the numbers are for the latest year
  - The data from the small arms survey is only from 2007. 


**Takeaways from this Dataset:**

- The United States has the highest gun ownership in the World. 

- Centra/South America leads on all murder stats, far ahead of US.
  - We think that deaths caused by firearms in Central and South America are due to drug activity and not because of personally owned firearms, since the same Central and South American countries have much lower amounts of gun ownership. 

- To capture the amount of homicides  due to personally owned guns we made a new interaction term - "hom_firearms", which is the average percent of homicides caused by firearms by the average number of firearms per 100 people.  Here we see that the US ranks the highest in the world.

In [0]:
df_world = df_world.rename(columns={'Country/Territory':'country', 
                   'ISO code': 'iso_code',
                   '% of homicides by firearm' : 'percent_hom_farm',
                   'Number of homicides by firearm' : 'num_hom_farm', 
                   'Homicide by firearm rate per 100,000 pop' : 'hom_farm_rate_100k',
                   'Rank by rate of ownership' : "rank_rate_ownership",
                   'Average firearms per 100 people' : 'avg_farm_100ppl',
                   'Average total all civilian firearms' : 'avg_tot_civ_farm'
                  }) 

df_world = df_world.drop(columns = "Source")
#Interaction Term
df_world['hom_firearms'] = (df_world['avg_farm_100ppl'] * df_world['percent_hom_farm'] )

In [0]:
df_world.head()

     country iso_code  ...  avg_tot_civ_farm  hom_firearms
0    Albania       AL  ...          270000.0        566.74
1    Algeria       DZ  ...         1900000.0         36.48
2     Angola       AO  ...         2800000.0           NaN
3   Anguilla       AI  ...               NaN           NaN
4  Argentina       AR  ...         3950000.0        530.40

[5 rows x 9 columns]

Feature | Description
--- | ---
**country** | the country name
**iso_code** | unique code for every country or territory
**source** | original data sources
**percent_hom_farm** | percent of homicides by firearms for every country
**num_hom_farm** | number of homicides by firearm
**hom_farm_rate_100k** | homicide by firearm rate per 100,000 people
**rank_rate_ownership** | rank by rate of ownership
**avg_farm_100ppl** | average firearms per 100 people
**avg_tot_civ_farm** | average of all total civilian firearms

## Gun Ownership Per State 

This accessory dataset shows gun ownership statistics per state. It will be used to merge onto the the *United States firearms dataset* and the *United States mass shootings dataset*. 

[Data Source](http://demographicdata.org/facts-and-figures/gun-ownership-statistics/#)


---

**Description of the Dataset:** 

- This dataset contains a complete set of crime rates, gun deaths and gun ownership rates. There are a total of 51 records and 12 fields which include crime types such as violent, murder, rape, robbery, assault, property, burglary, larceny and motor-related crimes. All data are grouped by state.

- The only statistic we are interested in for this dataset is gun ownership column to merge with the US Firearms Data and the Mass shootings data. 

- Limitations: 
  - Poorly documented how the data was compiled. It seems that the variable of interest, "Gun Ownership (2007)" was taken from the [General Social Survey (GSS)](http://www.norc.org/Research/Projects/Pages/general-social-survey.aspx) , but it is not clear why they used 2007 as the year of data in this aggregate dataset.

In [0]:
df_st_owner.head()

   State Name  ...  Motor Theft (per 100K) 2013
0     Alabama  ...                        204.8
1      Alaska  ...                        208.1
2     Arizona  ...                        292.3
3    Arkansas  ...                        194.1
4  California  ...                        443.2

[5 rows x 12 columns]

In [0]:
# Data Cleaning

# Drop unneccessary columns 
df_st_owner.drop(['Gun Murder Rate per 100K (2010)','Violent Crime  (per 100,000) 2013','Murder and nonnegligent manslaughter (per 100K) 2013',\
                  'Forcible rape (per 100K) 2013', 'Robbery (per 100K) 2013','Aggravated assault  (per 100K) 2013','Property Crime  (per 100K) 2013',\
                  'Burglary  (per 100K) 2013','Larceny (per 100K) 2013', 'Motor Theft (per 100K) 2013'],axis = 1, inplace = True)

# Rename the state column for ease of use and easier merging
df_st_owner.rename(columns = {'State Name': 'State', 'Gun Ownership (2007)': 'Gun_Ownership_2007'}, inplace = True)

# Change the values in gun ownership to a float for calculations
df_st_owner['Gun_Ownership_2007'] = df_st_owner['Gun_Ownership_2007'].str.rstrip('%').astype(float)/100
df_st_owner.sort_values(by = 'Gun_Ownership_2007', ascending=False).head(10)

            State  Gun_Ownership_2007
50        Wyoming               0.597
1          Alaska               0.578
26        Montana               0.577
41   South Dakota               0.566
48  West Virginia               0.554
12          Idaho               0.553
3        Arkansas               0.553
24    Mississippi               0.553
0         Alabama               0.517
34   North Dakota               0.507

## State Firearms Laws Data
This accessory dataset shows  of all law provisions by year and state as well as the codebook. It will be used to merge onto the the *United States firearms dataset* and the *United States mass shootings dataset*. 

[Data Source](https://www.statefirearmlaws.org/resources)

---

**Description of the Dataset:**

- Dataset was created by Boston University Public School of Health to report on the changing landscape of gun policy in the United States

- The data contains the gun laws per state per year from 1991 - 2018

- There are 133 firearm law provisions represented by dummy variable columns of weather a state in a certain year had that law in effect. 
   - The [report](http://sfal.communicatehealth.com/sites/default/files/2017-12/report_0.pdf) that details the laws in the database 

- **Limitations**:
  - The dataset only goes to 2018, so when merging with the other datasets it leads to null values.

In [0]:
df_state_laws.head()

        state  year  felony  ...  dvroremoval  stalking  lawtotal
0     Alabama  1991       0  ...            0         0        15
1      Alaska  1991       1  ...            0         0        10
2     Arizona  1991       0  ...            0         0        12
3    Arkansas  1991       1  ...            0         0        15
4  California  1991       1  ...            0         0        58

[5 rows x 137 columns]

In [0]:
# Only keep the year, state and the total number of laws 
df_state_laws = df_state_laws[['state', 'year', 'lawtotal']]

df_state_laws.head()

        state  year  lawtotal
0     Alabama  1991        15
1      Alaska  1991        10
2     Arizona  1991        12
3    Arkansas  1991        15
4  California  1991        58

#### We find the difference in the number of gun laws per state by subtracting the number of laws on book in 2018 by the number of laws on book in 2011.  We can merge this onto out mass shootings dataset to see how increasing or decreasing the number of gunlaws affects the number of mass shootings. 


While our mass shootings dataset only has data from 2013 to 2018, we consider that gun laws might have a lagged effect.

In [0]:
df_law_diff = df_state_laws[df_state_laws.year >2010].groupby('state').agg(lambda x: x.iloc[-1] - x.iloc[0])
df_law_diff = df_law_diff.reset_index()
df_law_diff = df_law_diff.rename(columns = {'lawtotal': 'Law_diff', 'state': 'State'}).drop(columns = 'year')
df_law_diff.head()

        State  Law_diff
0     Alabama        -1
1      Alaska        -1
2     Arizona         0
3    Arkansas        -2
4  California        15

## United States Firearms Data

**The firearm injury related deaths per state and year due to suicides, homicides and unintentional causes.**

---

**Description of the Dataset:**

- Data on fatal injuries due to firearm was taken from the [CDC](https://www.cdc.gov/injury/wisqars/fatal.html) fatal injury data. 

  - WISQARS Fatal’s mortality reports provide tables of the total numbers of injury-related deaths and the death rates per 100,000 population. The reports lists deaths according to cause (mechanism) and intent (manner) of injury by state, race, Hispanic origin, sex, and age groupings.
  
- Data was collected from 1999 - 2017.

- Mortality data reported in WISQARS come from death certificate data reported to the National Center for Health Statistics (NCHS), CDC. NCHS collects, compiles, verifies and prepares these data for release to the public.

- Data was filtered on firearms as the mechanism for 3 data exports:
  - The intent was filtered on suicides, homicides and unintentional causes separately and exported as 3 csv files. 
  - For ease of having one dataset, these csv files were combined in excel with the intent listed under "Type".

- Limitations: 
  - For sub-national geography, not present or publish death counts of 9 or fewer or death rates based on counts of nine or fewer are presnt as "P" for the value. Since these values are not reliable, they will be replaced with "0" for numerical representation. 

**citation:** Centers for Disease Control and Prevention, National Centers for Injury Prevention and Control. Web-based Injury Statistics Query and Reporting System (WISQARS) [online]. (2005) {cited 2019 May 16}. Available from: www.cdc.gov/injury/wisqars

---
Disclaimer: This data is used for a school research project to report on firearms analysis and may not be repurposed for anything other than statistical reporting and analysis. Make no attempt to learn the identity of any person or establishment included in these data.
Make no disclosure or other use of the identity of any person or establishment discovered inadvertently and advise the NCHS Confidentiality Officer of any such discovery.

"The data source for WISQARS Fatal Injury Data Visualization is the National Vital Statistics System (NVSS) operated by the National Center for Health Statistics. WISQARS provides death counts and death rates for the United States and by state, county, age, race, Hispanic ethnicity, sex, leading cause of death, injury intent, and injury mechanism categories. WISQARS can be used to query death data for the years 2001 - 2017, of which the underlying cause of death is specified using ICD-10 codes. The National Center for Health Statistics (NCHS) in an agreement with the National Association of Public Health Statistics and Information Systems (NAPHSIS) has implemented a new, more restrictive rule for reporting state- and county-level death data for years 2008 and later from NVSS in order to avoid inadvertent disclosure of a decedent's identity. Therefore, the Statistics, Programming and Economics Branch, Division of Analysis, Research, and Practice Integration, NCIPC has modified WISQARS to accommodate the new data suppression rule; i.e., no figure, including totals, should be less than 10 in tabulations for sub-national geographic areas, regardless of the number of years combined with the 2008 and later data. Tabulations, charts, and maps produced by WISQARS using only NVSS death data for years prior to 2008 are not affected by this new rule. Therefore, queries of state-level data for years 1999 through 2007 will remain unrestricted; queries of state-level data that include 2008 or later are restricted. As a WISQARS user, please read the following data use restrictions and click "I Agree." You will then be given access to this WISQARS module."

In [0]:
df_state.head()

          Sex       Race    State  ... Population Crude Rate  Age-Adjusted Rate
0  Both Sexes  All Races  Alabama  ...    4430143       1.15         1.15722772
1  Both Sexes  All Races  Alabama  ...    4451687       0.76         0.76222845
2  Both Sexes  All Races  Alabama  ...    4467634       0.92        0.926071313
3  Both Sexes  All Races  Alabama  ...    4480089          1        0.997164737
4  Both Sexes  All Races  Alabama  ...    4503491       0.84         0.82537211

[5 rows x 13 columns]

In [0]:
#### Data Cleaning ####

# Remove row of data that is the aggregate of all deaths per state across all years for a specific cause of death (this is done by removing the row of data where the year is null)
df_state = df_state[pd.notnull(df_state['Year'])]

# Rename columns for ease of use
df_state.rename(columns = {'Cause of Death':'cause_of_death'}, inplace = True)

# According to the disclaimers in the dataset, we will consider the value "P" a zero, knowing that "P" represents an uncertain death rate between 0-9.   
# We want to keep the data numerical and continuous, so replacing them with 0 is the best option.
df_state['Deaths'] = df_state['Deaths'].replace("P", 0)

# Check to make sure there are no null values
df_state.isna().sum()

# Drop unneccesary columns
df_state.drop(['Sex','Race','Ethnicity','Age Group','First Year','Last Year','Crude Rate',\
               'Age-Adjusted Rate'],axis = 1, inplace = True)

In [0]:
#### Merge ####

# Combine the state data with the percentage of gun owners and the amount of gun laws
df_state_tot = df_state.merge(df_st_owner, how = 'left', on = "State")

df_state_tot.Year.astype(int)
df_state_tot = df_state_tot.merge(df_state_laws, how = 'left', left_on = ['State', 'Year'],  right_on = ['state', 'year'])

df_state_tot.head()

     State         cause_of_death    Year  ...    state    year  lawtotal
0  Alabama  Unintentional Firearm  1999.0  ...  Alabama  1999.0      16.0
1  Alabama  Unintentional Firearm  2000.0  ...  Alabama  2000.0      11.0
2  Alabama  Unintentional Firearm  2001.0  ...  Alabama  2001.0      11.0
3  Alabama  Unintentional Firearm  2002.0  ...  Alabama  2002.0      11.0
4  Alabama  Unintentional Firearm  2003.0  ...  Alabama  2003.0      11.0

[5 rows x 9 columns]

In [0]:
#### Create New Columns ####

# Change 'Deaths' to float for calculation
df_state_tot['Deaths'] = pd.to_numeric(df_state_tot['Deaths'])

df_state_tot['Deaths_per_capita'] = df_state_tot['Deaths']/df_state_tot['Population']
df_state_tot['Deaths_x_guns'] = df_state_tot['Deaths']*df_state_tot['Gun_Ownership_2007']
df_state_tot['Deaths_percap_x_guns'] = df_state_tot['Deaths_per_capita']*df_state_tot['Gun_Ownership_2007']

Feature | Description
--- | ---
**State:** | The state name
**cause_of_death:** | Categorical Variable (Unintentional Firearm, Homicide/Legal Intervention Firearm, Suicide Firearm)
**Year:** | Year 1999-2017
**Deaths:** | The number of deaths per state per year per cause of death
**Population:** | The population per state per year
**Gun_Ownership_2007:** | The percent of people who own firearms in each state
**Deaths_per_capita:** | The number of gun related deaths divided by the population per state per year
**Deaths_x_guns:** | An interaction term of the number of gun related deaths multiplied by the percent of gun ownership in each state per year
**Deaths_percap_x_guns:** | An interaction term of the number of deaths per capita multiplied by the percent of gun ownership in each state per year
**lawtotal:** |The total number of gun laws per state per year

## Mass Shootings in the United States

**Deaths and injuries due to mass shootings in the US**

---

**Description of the Dataset:**

- Data on mass shootings was taken from [Mass Shooting Tracker](https://www.massshootingtracker.org/data), a website dedicated to recording all mass shootings that occur in the US.

- Data collected from 2013 - Present(2019).
  -  The data provided by the website is a csv file for each year, beginning in 2013. We combined the 7 files into one dataset in Excel for ease of use.
- Mass Shooting Tracker uses various valid news sources for their data, and records these sources in their dataset.
- The website defines a mass shooting as any firearm event involving in the injury or death of at least 4 people. 
- This data has been featured by CNN, MSNBC, The New York Times, The Washington Post, and The Economist
- Limitations:
   - This data is compiled by crowd-sourcing
   - While we would have liked to find a government funded data source on this topic,  Congress has effectively blocked the CDC from researching the underlying causes of gun violence as of December 2015, so this is a well compiled dataset from published researchers who volunteer their time. 

**citation:** Mass Shooting Tracker. (2019) {cited 2019 May 19}. Available from: https://www.massshootingtracker.org/data/all

In [0]:
df_ms.head()

      date  ...                        sources_semicolon_delimited
0  5/15/19  ...  https://abc7.com/3-men-5-year-old-girl-shot-at...
1  5/13/19  ...  https://www.stltoday.com/news/local/crime-and-...
2  5/13/19  ...  https://www.wdsu.com/article/four-injured-in-c...
3  5/12/19  ...  https://6abc.com/5-hurt-after-gunmen-open-fire...
4  5/11/19  ...  https://wnep.com/2019/05/11/four-people-shot-a...

[5 rows x 7 columns]

#### Each of the other cleaned data frames to merge onto the mass shootings data

In [0]:
# Mass shootings dataset only has the abreviated state names, so another dataset with the spelled out state names is brought in
df_state_code.head()

        State Abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [0]:
df_st_owner.head()

        State  Gun_Ownership_2007
0     Alabama               0.517
1      Alaska               0.578
2     Arizona               0.311
3    Arkansas               0.553
4  California               0.213

In [0]:
df_state_laws.rename(columns = {'state':'State'}, inplace = True)
df_state_laws.head()

        State  year  lawtotal
0     Alabama  1991        15
1      Alaska  1991        10
2     Arizona  1991        12
3    Arkansas  1991        15
4  California  1991        58

In [0]:
df_law_diff.head()

        State  Law_diff
0     Alabama        -1
1      Alaska        -1
2     Arizona         0
3    Arkansas        -2
4  California        15

In [0]:
# Population dataframe is made from the previous data set in order to create deaths per capita
df_population = df_state_tot.groupby(['State','year'])['Population'].mean().reset_index(name='Population')
df_population.head()

     State    year  Population
0  Alabama  1999.0     4430143
1  Alabama  2000.0     4451687
2  Alabama  2001.0     4467634
3  Alabama  2002.0     4480089
4  Alabama  2003.0     4503491

In [0]:
#### Create New Columns ####

df_ms.date = pd.to_datetime(df_ms.date)
df_ms['year'] = df_ms.date.dt.year

#### Create table for gun law change between 2013 and 2017

In [0]:
df_17lawtotal = df_state_laws[df_state_laws.year == 2017]
df_13lawtotal = df_state_laws[df_state_laws.year == 2013]
df_17lawtotal = df_17lawtotal.rename(columns = {'lawtotal': 'lawtotal_2017'}).drop(columns = 'year')
df_13lawtotal = df_13lawtotal.rename(columns = {'lawtotal': 'lawtotal_2013'}).drop(columns = 'year')
df_13_17_lawchange = df_13lawtotal.merge(df_17lawtotal, how = 'left', on = "State")
df_13_17_lawchange['numLawChange'] = \
df_13_17_lawchange.lawtotal_2017 - df_13_17_lawchange.lawtotal_2013

In [0]:
df_13_17_lawchange.head()

        State  lawtotal_2013  lawtotal_2017  numLawChange
0     Alabama             10             10             0
1      Alaska              3              3             0
2     Arizona              8              8             0
3    Arkansas             11             11             0
4  California             99            106             7

#### States with number of law change greater than or equal to 2

In [0]:
df_13_17_lawchange[(df_13_17_lawchange.numLawChange >= 2) | (df_13_17_lawchange.numLawChange <= -2)]

            State  lawtotal_2013  lawtotal_2017  numLawChange
4      California             99            106             7
6     Connecticut             84             90             6
7        Delaware             37             40             3
9         Georgia             11              6            -5
11          Idaho              5              2            -3
13        Indiana             10             12             2
15         Kansas              8              4            -4
17      Louisiana              8             13             5
22      Minnesota             31             41            10
23    Mississippi              5              2            -3
24       Missouri              8              2            -6
27         Nevada             11             21            10
29     New Jersey             67             75             8
31       New York             73             76             3
33   North Dakota             14             10            -4
36         Oregon             24             35            11
38   Rhode Island             45             53             8
41      Tennessee             24             22            -2
42          Texas             20             18            -2
43           Utah             11             13             2
44        Vermont              3              6             3
46     Washington             25             43            18
47  West Virginia             24             18            -6

In [0]:
# States with positive number of law change greater than or equal to 2: 14 states
df_13_17_lawchange[(df_13_17_lawchange.numLawChange >= 2)]

           State  lawtotal_2013  lawtotal_2017  numLawChange
4     California             99            106             7
6    Connecticut             84             90             6
7       Delaware             37             40             3
13       Indiana             10             12             2
17     Louisiana              8             13             5
22     Minnesota             31             41            10
27        Nevada             11             21            10
29    New Jersey             67             75             8
31      New York             73             76             3
36        Oregon             24             35            11
38  Rhode Island             45             53             8
43          Utah             11             13             2
44       Vermont              3              6             3
46    Washington             25             43            18

In [0]:
# States with positive number of law change greater than or equal to 2: 9 states
df_13_17_lawchange[(df_13_17_lawchange.numLawChange <= -2)]

            State  lawtotal_2013  lawtotal_2017  numLawChange
9         Georgia             11              6            -5
11          Idaho              5              2            -3
15         Kansas              8              4            -4
23    Mississippi              5              2            -3
24       Missouri              8              2            -6
33   North Dakota             14             10            -4
41      Tennessee             24             22            -2
42          Texas             20             18            -2
47  West Virginia             24             18            -6

#### Merge the gun ownership, the amount of gun laws per year per state, number of	law changed overtime, and	population per year per state on the mass shootings dataset

In [0]:
df_ms_tot = df_ms.copy()
df_ms_tot = df_ms.merge(df_state_code, how ='left', left_on = 'state', right_on = 'Abbreviation')
df_ms_tot = df_ms_tot.merge(df_st_owner, how = 'left', on='State')
df_ms_tot = df_ms_tot.merge(df_state_laws, how = 'left', on = ['State', 'year'])
df_ms_tot = df_ms_tot.merge(df_law_diff, how = 'left', on = 'State')
df_ms_tot = df_ms_tot.merge(df_population, how = 'left', on = ['State', 'year'])

In [0]:
df_ms_tot.drop(['name_semicolon_delimited','sources_semicolon_delimited', 'state', 'Abbreviation'],axis = 1, inplace = True)

In [0]:
#### Create New Columns ####

df_ms_tot['shot'] = df_ms_tot.killed + df_ms_tot.wounded
df_ms_tot['shot_x_gun_owner'] = df_ms_tot.shot*df_ms_tot['Gun_Ownership_2007']
df_ms_tot['killed_x_gun_owner'] = df_ms_tot.killed*df_ms_tot['Gun_Ownership_2007']
df_ms_tot['death_each_year'] = df_ms_tot.groupby(['State','year'])['killed'].transform('sum')
df_ms_tot['Deaths_per_capita'] = df_ms_tot['death_each_year']/df_ms_tot['Population']

Feature  | Descriptions 
--- | ---
**date:** | Date when the shooting happened 
**killed:** | The number of people killed
**wounded:** | The number of people wounded
**city:** |The city where the shooting took place
**State:** |The state where the shooting took place
**Gun_Ownership_2007:** |The percent of people who own guns per state
**year:** |The year when the shooting happened
**weekday:** |The day of the week that the shooting took place
**shot:** |The number of people either killed or wounded in a mass shooting
**shot_x_gun_owner:** |The interaction term of the number of people who were shot in a mass shooting multiplied by the percent of gun owners in that state where the shooting occurred. 
**killed_x_gun_owner:** |The interaction term of the number of people who were killed in a mass shooting multiplied by the percent of gun owners in that state where the shooting occurred. 
**lawtotal:**| The total number of gun laws per state per year
**Law_diff:** |The difference in the number of gun laws per state from 2011 thru 2018 (negative means that there is a decrease in the number of gun laws)
**Population:** |The population per state per year (data only available until 2017)
**death_each_year:** |The number of people killed in mass shootings per state per year
**Deaths_per_capita:** |The number of mass shooting deaths per state per year divided by the population per state per year from 2013 to 2017 (NaN for 2018 and 2019, since population data only available until 2017).

## Roadmap

For our narrative, we want to focus on our logistical flow for our arguments. Our next step is to smoothly transition our arguments from higher levels of analysis to more granular levels of analysis.

We begin at the International level and transition into United States' state level data and finally into domestic mass shootings. Initially, we identify that the United States is the leader for homicides by personal guns. Then, we transitioned to compare gun laws at a state level within the United States. Our argument for these visualizations stems from the relationship between deaths and laws. With increasing laws, there is a decrease in overall deaths. Focusing on mass shootings, increased gun regulation results in fewer deaths.

We want to forefront the most crucial attribute of our visualizations with respect to our argument to enable the flow. We want to finalize and polish each of our visualizations by editing features such as better titles, trend lines, descriptive charts, labeling, legends, and other attributes.

Keeping in mind that the most important aspect to persuade and audience, we want to target both policy makers and voters. Our goal is to persuade the audience that more gun regulations results in decreased overall deaths.

### As we saw from the previous data set, the United states had the highest amount of deaths due to guns in the world. When investigating the amount of deaths by state we can see that states vary in the amount of gun deaths per capita. Here we explore different reasons for the variation and potential solutions.   Perhaps the root cause is the number of gun laws a state has.

### States with less gun laws have higher deaths per capita 

At the world level, we wanted to look at deaths caused by legal gun owners, and found that the US, which has comparitively lax gun laws, has a high number of deaths by legal gun owners. 

We wanted to see if this trend persists within the US at a state level.  To test this, we compared the total number of gun laws in a state, with the average deaths per capita of that state.  The mirrored bar chart below shows the relationship between these two variables.  

Like in the world dataset, we found that when gun laws are lax, you will see more deaths per capita in general  

This is the Tableau Public link:

https://public.tableau.com/profile/kevin.chang5623#!/vizhome/lesslaws_moredeaths/lawsvsdeathpercapita?publish=yes

### Effects of less gun laws: More gun ownership, and more mass shootings 

Once we created the categories of High Gun laws, and Low Gun Laws, we wanted to see how these laws would affect the poeple in the state.  

As a sanity check, we compared the gun ownership between these two categories, and found that, unsurprisingly, states with low gun laws have higher gun ownership.  This finding is shown in the **left** bar chart.

Then, we wanted to identify if states with fewer gun laws had more mass shootings then states with many gun laws.  As shown by the **right** chart, states with Low Gun Laws have a higher number of mass shootings compared to High Gun Law states.

The total gun laws are aggregated at the state and year level were split into two groups:

* **Low Gun Laws** are states that have between 2-45 total gun laws on the books
* **High Gun Laws** are states that have between 63-109 total gun laws on the books

### States that added more gun laws have fewer gun deaths 

In the previous visualization, we examined the differences between states with many gun laws, and states with few gun laws.  This provided valuable insight, but it only compared data between states.  With the visualizations below, we wanted to compare mass shooting data within individual states.

To do this, we used the variable law_diff, which is the difference gunlaws between 2018 and 2011.  Using law_diff, we were able to group all states into three categories: states that increased their gun laws, states that decreased their gun laws, and states that did not have a change in gun laws.  

We wanted to see if there were any differences between these groups.  From the visualization on the **left**, we can see that states that increased the number of gun laws have less people killed by legal gun owners.  From the visualization on the **right**, we can see that states that increased the number of gun laws also have fewer gun deaths per capita.  

We think this is evidence to support increased gun regulation.

The change in gun laws were calculated as the difference between the number of gun laws in 2011 and 2018 per state.
* **No Law Change** are states that had zero change in gun laws
* **Increased Laws** are states that had positive change in gun laws (from 1 thru 19)
* **Decreased Laws** are states that had negative change in gun laws (from -6 thru -1)

### Our findings was corroborated in Missouri and Oregon

These line plots give us a state-level look at the effects of changing gun laws.  

We wanted to show the relationship between the number of gun laws, versus the number of people shot by gun owners.  In Missouri, we see that when gun laws were repealled, the number of people who were shot increased.  Conversely, in Oregon, when additional gun laws were passed, the number of people who were shot decreased.  

The key finding is that changing gun laws produces an immediate, measurable impact on the number of people shot by legal owners in Missouri and Oregon.  At the very least, our prior finding held true in these two states.  In conclusion, we feel that gun regulation should be increased for the entire country.